export const onboardingServiceCatalog = [
  {
    key: "corte-feminino",
    name: "Corte feminino",
    description: "Corte com finalização básica para atendimento padrão do salão.",
    durationMinutes: 60,
    priceInCents: 9000,
  },
  {
    key: "escova",
    name: "Escova",
    description: "Escova e modelagem para rotina de atendimento rápido.",
    durationMinutes: 45,
    priceInCents: 6500,
  },
  {
    key: "manicure",
    name: "Manicure",
    description: "Atendimento de manicure tradicional.",
    durationMinutes: 45,
    priceInCents: 4000,
  },
  {
    key: "pedicure",
    name: "Pedicure",
    description: "Atendimento de pedicure tradicional.",
    durationMinutes: 60,
    priceInCents: 5000,
  },
  {
    key: "alongamento-de-unhas",
    name: "Alongamento de unhas",
    description: "Aplicação e manutenção de alongamento de unhas.",
    durationMinutes: 90,
    priceInCents: 12000,
  },
  {
    key: "design-de-sobrancelhas",
    name: "Design de sobrancelhas",
    description: "Design e alinhamento de sobrancelhas.",
    durationMinutes: 30,
    priceInCents: 3500,
  },
  {
    key: "hidratacao-capilar",
    name: "Hidratação capilar",
    description: "Tratamento capilar de hidratação.",
    durationMinutes: 75,
    priceInCents: 8500,
  },
  {
    key: "maquiagem",
    name: "Maquiagem",
    description: "Maquiagem social para eventos e produção.",
    durationMinutes: 90,
    priceInCents: 15000,
  },
] as const;

export const brazilStates = [
  "AC",
  "AL",
  "AP",
  "AM",
  "BA",
  "CE",
  "DF",
  "ES",
  "GO",
  "MA",
  "MT",
  "MS",
  "MG",
  "PA",
  "PB",
  "PR",
  "PE",
  "PI",
  "RJ",
  "RN",
  "RS",
  "RO",
  "RR",
  "SC",
  "SP",
  "SE",
  "TO",
] as const;
